[package]
name = "substrate-core-impl"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
substrate-core-spec = { path = "../substrate-core-spec" }
cfg-if = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
petgraph = { version = "0.8" }
wide = { version = "1.1", optional = true }
rayon = { version = "1.11", optional = true }
kaio = { version = "0.4", optional = true }
kaio-ops = { version = "0.4", optional = true }
pollster = { version = "0.4", optional = true }
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
rumqttc = { version = "0.25", optional = true }
dust_dds = { version = "0.14", optional = true }
opcua = { version = "0.12", optional = true }
rand = "0.10.1"
rand_distr = "0.6.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pprof = { version = "0.15", features = ["flamegraph", "criterion"] }

[build-dependencies]
cc = "1.0"

[features]
default = ["std"]
std = []
simd = ["dep:wide"]
parallel = ["dep:rayon"]
gpu = ["dep:kaio", "dep:kaio-ops", "dep:pollster"]
fast = ["simd", "parallel"]
mqtt = ["dep:rumqttc"]
dds = ["dep:dust_dds"]
opcua = ["dep:opcua"]

[[bench]]
name = "array_benchmark"
harness = false

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
