[package]
name = "substrate-core-py"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "substrate_core"
crate-type = ["cdylib"]

[dependencies]
substrate-core-spec = { path = "../substrate-core-spec" }
substrate-core-impl = { path = "../substrate-core-impl" }
pyo3 = { version = "0.28", features = ["extension-module"] }

[dev-dependencies]